In [1]:
import numpy

# initializing matrices
x = numpy.array([[5, 9], [1, 3]])
y = numpy.array([[1, 2], [8, 2]])

# using add() to add matrices
print("The element wise addition of matrix is : ")
print(numpy.add(x, y))

# using subtract() to subtract matrices
print("The element wise subtraction of matrix is : ")
print(numpy.subtract(x, y))

# using dot() to multiply matrices
print ("The product of matrices is : ")
print (numpy.dot(x,y))

# using "T" to transpose the matrix
print("The transpose of given matrix is : ")
print(x.T)

The element wise addition of matrix is : 
[[ 6 11]
 [ 9  5]]
The element wise subtraction of matrix is : 
[[ 4  7]
 [-7  1]]
The product of matrices is : 
[[77 28]
 [25  8]]
The transpose of given matrix is : 
[[5 1]
 [9 3]]
